### ISSUE TITLE
Panic if Load() is called before Store()

### ISSUE THREAD

**Issue by Jacalz** [uber-go/atomic#102]
I am getting this error when `Load()` happens before a call to `Store()` (with bool as an example here).
```
[jacob@fedora fyne_demo]$ ./fyne_demo 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x816bba]

goroutine 1 [running, locked to thread]:
go.uber.org/atomic.(*Bool).Load(...)
	/home/jacob/go/pkg/mod/go.uber.org/atomic@v1.9.0/bool.go:49

```

I would personally have expected this to behave similarly to a regular type that would have it's default value returned when trying to access it before it has been changed. This would make the package a lot more useful for my use cases as I can avoid a lot of constructors or `sync.Once` by just letting the atomic types be part of the struct fields and then stored when it changes.

**Comment by prashantv** [comment]
If `Load()` is called on an uninitialized `atomic.Bool`, it returns the default value, false,
```go
	var b atomic.Bool
	fmt.Println(b.Load())
```
https://play.golang.org/p/qxakAGECo19

In your case, I think the issue is that you have a _pointer_ to an `atomic.Bool`.

**Comment by Jacalz** [comment]
You're right. I must have accidentally left the point on there from before I rewrote it to use atomic. Sorry.
