### ISSUE TITLE
Provide atomic type for float32 as well

### ISSUE THREAD

**Issue by Jacalz** [uber-go/atomic#103]
It would be very useful to have a similar atomic version for float32 as well for use cases where the precision of float64 is not necessary.

**Comment by abhinav** [comment]
Sure thing! We'd welcome a PR implementing that.
The implementation should be pretty similar to Float64,
but using [math.Float32bits](https://pkg.go.dev/math#Float32bits) and [math.Float32frombits](https://pkg.go.dev/math#Float32frombits) instead.

**Comment by sywhang** [comment]
Closed by #107.
