### ISSUE TITLE
Compatible  with atomic.Pointer with golang 1.19

### ISSUE THREAD

**Issue by woodliu** [uber-go/atomic#115]
Hi，golang 1.19 has support atomic.Pointer, how do you compatible  with this feature? Thanks!
[Atomic Pointers in Go 1.19](https://betterprogramming.pub/atomic-pointers-in-go-1-19-cad312f82d5b)

**Comment by abhinav** [comment]
We don't yet, but I think we can provide an alias for `atomic.Pointer` for Go 1.19 and beyond.
We could also include a re-implementation of it for Go 1.18.
