### ISSUE TITLE
Atomic String Swap panics if created with empty string

### ISSUE THREAD

**Issue by KromDaniel** [uber-go/atomic#126]
Hey,

I've encountered the following issue with atomic.String

```go
atomicStr := atomic.NewString("")
atomicStr.Swap("string")
```

error
```go
panic: interface conversion: interface {} is nil, not string [recovered]
	panic: interface conversion: interface {} is nil, not string
	
go.uber.org/atomic.(*String).Swap(...)
	/Users/dkrom/Dev/gonzo/pkg/mod/go.uber.org/atomic@v1.10.0/string.go:64
```

I guess its because NewString condition

```go
func NewString(val string) *String {
	x := &String{}
	if val != _zeroString {
		x.Store(val)
	}
	return x
}
```

I'm not sure if its by design or not?

go version go1.19.4 darwin/arm64
atomic @v1.10.0

Thanks a lot!

**Comment by eNV25** [comment]
Needs fixing in Swap method to match Load.

https://github.com/uber-go/atomic/blob/78a3b8ec6cb2e156b91140c7d53b16e12b7b3f91/internal/gen-atomicwrapper/wrapper.tmpl#L94-L100
