### ISSUE TITLE
Why NewError need judge _zeroError

### ISSUE THREAD

**Issue by langgo** [uber-go/atomic#135]
https://github.com/uber-go/atomic/blob/544d6aa5c2660469459c390a8e3d2a3db58d182c/error.go#L37

Why NewError need judge _zeroError
because I want to use this code to store the first error
```
err := NewError(nil)
err.CompareAndSwap(nil, errors.New("error message"))
```

because of _zeroError 
I must use 
```
err := NewError(nil)
err.Store(nil)
err.CompareAndSwap(nil, errors.New("error message"))
```

**Comment by JacobOaks** [comment]
Hey @langgo,

We think that this should work with the latest head of master ([this line](https://github.com/uber-go/atomic/blob/544d6aa5c2660469459c390a8e3d2a3db58d182c/error.go#L59) seems to check for your case).
Can you try pinning to master HEAD and seeing if that resolves your issue?

In the meantime we should probably cut a release soon. Internal ref: GO-2012

**Comment by tchung1118** [comment]
v1.11.0 was released last week, and that should resolve this issue.
