### ISSUE TITLE
Failing unit tests on i686 architecture (RISC-V): constant 18446744073709551615 overflows uintptr

### ISSUE THREAD

**Issue by Hellseher** [uber-go/atomic#164]
Hi,

During package review requiring to update Kubo (IPfs) in Guix, I've faced with
an issue when I try to build github.com/uber/atomic@1.8.0 on i686-linux machine:

```
# go.uber.org/atomic [go.uber.org/atomic.test]
src/go.uber.org/atomic/uintptr_test.go:72:29: constant 18446744073709551615 overflows uintptr
FAIL    go.uber.org/atomic [build failed]
FAIL
```

To reproduce the issue:
```
guix time-machine --commit=42b4580f6bfcaab009a56e679bd6f3c408ef03c9 -- \
    build --system=i686-linux go-go-uber-org-atomic
```

Thanks,
Oleg

**Comment by JacobOaks** [comment]
Hey Oleg, can you clarify which version you're running on?

That line number is meaningless on master, and unless I'm missing something atomic doesn't have a version 18.0. Thanks.

**Comment by prashantv** [comment]
This looks similar to #99 which was fixed in #100.

**Comment by Hellseher** [comment]
@JacobOaks it's v1.8.0, I've updated the comment.

**Comment by JacobOaks** [comment]
@Hellseher can you try to upgrade to v1.11.0 which includes the fix mentioned by @prashantv? Let us know if that doesn't resolve the issue.

**Comment by Hellseher** [comment]
@JacobOaks I can confirm, updating atomic to the latest version (v1.11.0)
resolved the test failing issue on RISK-V.

Thanks for the suggestion, clossing as resolved.

Oleg.
