### ISSUE TITLE
support json encode decode for Pointer

### ISSUE THREAD

**Issue by trim21** [uber-go/atomic#178]
many atomic value support `MarshalJSON` and `UnmarshalJSON`, any plan for `Pointer[T]`?

**Comment by JacobOaks** [comment]
Hey, to better understand - how are you running into this issue/what's your use case?

**Comment by trim21** [comment]
> Hey, to better understand - how are you running into this issue/what's your use case?

i have a config file will be used in multiple goroutine, I don't want to write a duplicate thread safe structure
