### ISSUE TITLE
Add noCopy?

### ISSUE THREAD

**Issue by jeeyoungk** [uber-go/atomic#38]
I was wondering whether the `noCopy` struct should be embedded to all of the atomic structs, as it is undefined to copy these values around without corresponding Load / Store operations.

if we embed noCopy as empty struct there shouldn't be any performance hit on struct sizes.

**Comment by jeeyoungk** [comment]
https://github.com/valyala/fasthttp/blob/master/nocopy.go is one of the example.

**Comment by abhinav** [comment]
Per this comment https://github.com/uber-go/atomic/pull/39#pullrequestreview-116582332, this is probably inadvisable since noCopy would break those usages. Closing.
