### ISSUE TITLE
Can add Int and Uint?

### ISSUE THREAD

**Issue by runner-mei** [uber-go/atomic#47]

**Comment by prashantv** [comment]
This package wraps the operations in the standard library atomic package:
https://golang.org/pkg/sync/atomic/

`int` and `uint` don't have functions in that package, and they have different sizes based on architecture. We could assume worst-case and add functions that assume `int64` or `uint64`, but the user can easily do the same.

The most "correct" solution would be if `int` and `uint` used either the 32-bit or 64-bit types underneath based on architecture -- but I'd also want to have the code be architecture agnostic.

**Comment by tisonkun** [comment]
Yep. `int` and `uint` are os dependent and `atomic` doesn't support it. I think we can close this issue unless others give a more in-detail reason and how to support them.

**Comment by tisonkun** [comment]
cc @abhinav

**Comment by abhinav** [comment]
Reasonable. Thanks @tisonkun.
