### ISSUE TITLE
Improve JSON marshaling

### ISSUE THREAD

**Issue by tmm1** [uber-go/atomic#49]
If I have a struct with some atomic fields and try to marshal to json, all the json values are simply {}

Would be nice to have MarshalJSON() implementations for each type which return the underlying value by calling Load()

**Comment by dmalmer** [comment]
Created a PR to fix this as I needed this as well, but in the meantime you can always workaround this with something like:
```
type MarshalableAtomicFloat64 struct {
        uatomic.Float64
}

func (f *MarshalableAtomicFloat64) MarshalJSON() ([]byte, error) {
        return json.Marshal(f.Load())
}
```
And just use the `MarshalableAtomicFloat64` for your atomic calculations.
