### ISSUE TITLE
Disallow comparisons

### ISSUE THREAD

**Issue by abhinav** [uber-go/atomic#72]
Currently, it's possible to do,

```go
x := atomic.NewInt32(1)
y := atomic.NewInt32(2)

fmt.Println(*x == *y)
```

This accesses the value of the integer in a non-atomic way.

We should consider disabling this by adding a `_ [0]func()` field to the
atomic structs. This would add no runtime cost and disable struct-level
comparison of the values. (Ref: https://github.com/go4org/mem/blob/3dbcd07079b881f9bedb802b4099856c1e267fa1/mem.go#L42.)

Worth considering that this could constitute a breaking change. An argument
for in favor of the change is that the comparison was incorrect usage in the
first place, so it's not breaking to disallow it.

**Comment by prashantv** [comment]
Not allowing comparisons is a good idea. 

> An argument for in favor of the change is that the comparison was incorrect usage in the first place, so it's not breaking to disallow it.

Agree.
