### ISSUE TITLE
How to use `gen.go`?

### ISSUE THREAD

**Issue by tisonkun** [uber-go/atomic#89]
I don't find the dependent command `bin/gen-atomicint`.

**Comment by tisonkun** [comment]
Well. I can see the related code located at `internal` folder. But it requires manually build and copy.

**Comment by abhinav** [comment]
Hey there! You need to use `make generate` to have `gen-atomicint` do its thing.

`make generate` will build the binaries and place them under bin/, and then run `go generate ./...` to use them.

Hope this helps! Closing.

**Comment by tisonkun** [comment]
Thanks for your explanation!
